version: "3.7"

services:
  migration:
    image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
    network_mode: "host"
    command: ./neo migrate
    container_name: migration
    hostname: migration
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
  recalculable:
    image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
    network_mode: "host"
    command: ./neo recalculable --limit ${RECAL_QUEUE_LIMIT} --trigger ${RECAL_QUEUE_MINIMUM}
    container_name: recalculable
    hostname: recalculable
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
  recalulator:
    image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
    network_mode: "host"
    command: ./neo recalculate --worker ${RECAL_NUM_WORKERS}
    container_name: recalulator
    hostname: recalulator
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
  history:
    image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
    network_mode: "host"
    command: ./neo history --maxdate ${HISTORY_MAX} --mindate ${HISTORY_MIN} --datehold ${HISTORY_DATEHOLD} --threshold ${HISTORY_THRESHOLD}
    container_name: recalulator
    hostname: recalulator
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
