version: "3.7"

services:
  migration:
    image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
    network_mode: "host"
    command: ./neo migrate
    container_name: migration
    hostname: migration
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
